[versions]
# @keep
jacoco = "0.8.8"
logback = "1.4.14"
spring-boot = "3.2.0"

[libraries]
archunit-junit5 = "com.tngtech.archunit:archunit-junit5:1.2.1"
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
lombok = { module = "org.projectlombok:lombok" }
mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.8.0"
reactor-netty-http = "io.projectreactor.netty:reactor-netty-http:1.1.13"
reactor-test = { module = "io.projectreactor:reactor-test" }
snakeyaml = "org.yaml:snakeyaml:2.2"
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

[plugins]
dependency-license-report = "com.github.jk1.dependency-license-report:2.5"
sonarqube = "org.sonarqube:4.4.1.3373"
spotless = "com.diffplug.spotless:6.24.0"
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = "io.spring.dependency-management:1.1.4"
test-logger = "com.adarshr.test-logger:4.0.0"
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.1"
versions = "com.github.ben-manes.versions:0.50.0"
