[versions]
# @keep
jacoco = "0.8.12"
spring-boot = "3.3.3"

[libraries]
archunit-junit5 = "com.tngtech.archunit:archunit-junit5:1.3.0"
lombok = { module = "org.projectlombok:lombok" }
mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.13.0"
reactor-test = { module = "io.projectreactor:reactor-test" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

[plugins]
dependency-license-report = "com.github.jk1.dependency-license-report:2.9"
sonarqube = "org.sonarqube:5.1.0.4882"
spotless = "com.diffplug.spotless:6.25.0"
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = "io.spring.dependency-management:1.1.6"
test-logger = "com.adarshr.test-logger:4.0.0"
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.4"
versions = "com.github.ben-manes.versions:0.51.0"
